In [3]:
import numpy as np

1-Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

Cevap : Vektorler 1 boyutludur. Matrisler ise birden cok boyutludurlar.

In [3]:
#2- 10 elemanli bir listeden NumPy Array’i olusturunuz.

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#3- Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
#4- Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

np.ones((10,10),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
#5- Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

np.full((10,10), 9, dtype=int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [5]:
#6- 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [6]:
#7- -1 ile 1 arasinda 30 adet Array olusturunuz.

np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [7]:
#8- 0 ile 30 arasinda 5x6’lik bir matris olusturun.

np.arange(0,30).reshape((5,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [8]:
#9- Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

a=np.eye(10,10)
a


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
#10- 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; • eleman sayisini • 
# boyut bilgisini/sayisini • satir X sutun bilgisini • veri tipini numpy metodlariyla yazdiriniz.

b=np.random.randint(10, size = (5,10),dtype=int)
print(b)
print("Eleman Sayisi=",b.size)
print("Boyut Sayisi=",b.ndim)
print("Satir X Sutun =",b.shape)
print("Data Tipi=",b.dtype)

[[4 7 5 1 7 2 5 0 6 2]
 [1 9 3 9 1 0 5 1 2 3]
 [7 2 2 8 3 2 6 5 4 7]
 [1 4 7 2 6 3 0 5 6 3]
 [1 0 6 3 0 5 1 4 6 0]]
Eleman Sayisi= 50
Boyut Sayisi= 2
Satir X Sutun = (5, 10)
Data Tipi= int32


In [10]:
#11- 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

ax = np.random.randint(10, size=(3,7))
three_d = np.array([ax,ax,ax])
print(three_d)

[[[2 1 7 9 8 7 2]
  [1 4 4 2 5 0 5]
  [5 7 4 3 5 7 0]]

 [[2 1 7 9 8 7 2]
  [1 4 4 2 5 0 5]
  [5 7 4 3 5 7 0]]

 [[2 1 7 9 8 7 2]
  [1 4 4 2 5 0 5]
  [5 7 4 3 5 7 0]]]


In [11]:
#12- Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

vector = np.array([1,2,3,4,5,6,11,12,13,14,15,16])
rs = vector.reshape(3, 2,2)
print(vector)
print(rs)

[ 1  2  3  4  5  6 11 12 13 14 15 16]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [11 12]]

 [[13 14]
  [15 16]]]


In [12]:
#13- 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

x= np.array([1,2,3])
y= np.array([4,5,6])
z= np.array([7,8,9])
t= np.array([10,11,12])

con=np.concatenate([x,y,z,t])
con

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
#14- 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#15- Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

# "axis=0" matristeki satirlari temsil ediyor. Yukaridaki ornekte eger axis=0 kullansaydik matris satir bazinda birlestirilecekti.
# "axis=1" matristeki sutunlari temsil ediyor.


In [14]:
#16- Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,20,30]])

print("axis=0 :\n",np.concatenate((a, b), axis=0))
print("axis=1 :\n",np.concatenate((a, b.T), axis=1))



axis=0 :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
axis=1 :
 [[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [15]:
#17- 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

list = [1,2,3,4,5,6,7,8,9,10]
list_n = np.array(list)
np.split(list_n, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [16]:
#18- Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin 
# hangi indexte oldugunu gosteren bir metod uygulayiniz.

rand = np.random.randint(0,10, size=5)
sorted_rand = np.sort(rand)[::-1]
j=0
for i in (sorted_rand):
    print(f"{j}.index=",i)
    j+=1






0.index= 8
1.index= 8
2.index= 4
3.index= 3
4.index= 1


In [17]:
#19- 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

r20=np.random.randint(0,20, size=20)
print(r20)
r20[3:9:2]


[ 8 16 18  0  9 15  8  2 15 18 12  4  9 15 17 18 19 17  4  9]


array([ 0, 15,  2])

In [18]:
#20- 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

r10=np.random.randint(0,20, size=10)
print(r10)
r10[4]=100
print(r10)


[ 7  9  4 15  7 18  6  6 11 11]
[  7   9   4  15 100  18   6   6  11  11]


In [ ]:
#21- “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten 
# kucuk bir aciklama yaziniz.




In [19]:
# 22- 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
l=5
dia_5 = np.diag(np.random.randint(1,10,size=l))
print(dia_5)

for i in range(l):
    print(f"{i}.index'in Diagonali :",dia_5[i,i])





[[8 0 0 0 0]
 [0 2 0 0 0]
 [0 0 9 0 0]
 [0 0 0 6 0]
 [0 0 0 0 1]]
0.index'in Diagonali : 8
1.index'in Diagonali : 2
2.index'in Diagonali : 9
3.index'in Diagonali : 6
4.index'in Diagonali : 1


In [20]:
# 23- 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

vek_23=np.arange(10,20)
print(vek_23)

print(vek_23[3:])

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17 18 19]


24- 10X10 luk bir matris olusturunuz ve ; 

24a - 3.satir ve 5.sutuna ulasiniz. 
24b - 5.sutunun tum satirlarina ulasiniz. 
24c - Tum sutunlarin 2.satirlarina ulasiniz. 
24d - tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
24e - satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
24f - satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
24g - sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
24h - 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
NOT : elemanlara ulasirken; eleman-1 = index olarak alinmistir (2.eleman = 1.index)

In [21]:
#24- 10X10 luk bir matris olusturunuz.

matrix_24=np.random.randint(10,20,(10,10))
matrix_24

array([[13, 10, 13, 14, 17, 17, 17, 18, 15, 15],
       [17, 12, 16, 18, 13, 14, 19, 14, 19, 12],
       [15, 18, 18, 11, 18, 19, 16, 19, 10, 15],
       [18, 12, 13, 11, 17, 12, 15, 15, 16, 10],
       [15, 15, 12, 19, 16, 14, 14, 14, 14, 13],
       [19, 14, 11, 16, 17, 11, 15, 18, 12, 12],
       [12, 16, 19, 14, 13, 11, 17, 17, 10, 12],
       [17, 18, 15, 19, 10, 15, 14, 16, 18, 16],
       [11, 11, 18, 18, 15, 11, 14, 12, 13, 13],
       [19, 15, 14, 13, 17, 19, 19, 17, 19, 13]])

In [22]:
#24a- 3.satir ve 5.sutuna ulasiniz. 
matrix_24[2,4]

18

In [23]:
#24b- 5.sutunun tum satirlarina ulasiniz.
matrix_24[:,4]


array([17, 13, 18, 17, 16, 17, 13, 10, 15, 17])

In [24]:
#24c- Tum sutunlarin 2.satirlarina ulasiniz. 
matrix_24[1,:]

array([17, 12, 16, 18, 13, 14, 19, 14, 19, 12])

In [25]:
#24d- tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
matrix_24[1:7,:]

array([[17, 12, 16, 18, 13, 14, 19, 14, 19, 12],
       [15, 18, 18, 11, 18, 19, 16, 19, 10, 15],
       [18, 12, 13, 11, 17, 12, 15, 15, 16, 10],
       [15, 15, 12, 19, 16, 14, 14, 14, 14, 13],
       [19, 14, 11, 16, 17, 11, 15, 18, 12, 12],
       [12, 16, 19, 14, 13, 11, 17, 17, 10, 12]])

In [26]:
#24e- satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
matrix_24[2:5,3:7]

array([[11, 18, 19, 16],
       [11, 17, 12, 15],
       [19, 16, 14, 14]])

In [27]:
#24f- satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
matrix_24[5:,:4]

array([[19, 14, 11, 16],
       [12, 16, 19, 14],
       [17, 18, 15, 19],
       [11, 11, 18, 18],
       [19, 15, 14, 13]])

In [28]:
#24g- sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
matrix_24[:,3:10:3]

array([[14, 17, 15],
       [18, 19, 12],
       [11, 16, 15],
       [11, 15, 10],
       [19, 14, 13],
       [16, 15, 12],
       [14, 17, 12],
       [19, 14, 16],
       [18, 14, 13],
       [13, 19, 13]])

In [29]:
#24h- 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

matrix_24[5,5]=1987
matrix_24

array([[  13,   10,   13,   14,   17,   17,   17,   18,   15,   15],
       [  17,   12,   16,   18,   13,   14,   19,   14,   19,   12],
       [  15,   18,   18,   11,   18,   19,   16,   19,   10,   15],
       [  18,   12,   13,   11,   17,   12,   15,   15,   16,   10],
       [  15,   15,   12,   19,   16,   14,   14,   14,   14,   13],
       [  19,   14,   11,   16,   17, 1987,   15,   18,   12,   12],
       [  12,   16,   19,   14,   13,   11,   17,   17,   10,   12],
       [  17,   18,   15,   19,   10,   15,   14,   16,   18,   16],
       [  11,   11,   18,   18,   15,   11,   14,   12,   13,   13],
       [  19,   15,   14,   13,   17,   19,   19,   17,   19,   13]])

25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

25a - 20 den buyuk olan kac deger var.
25b - 30’dan kucuk kac deger var 
25c - icerisinde 33 gecen kac deger var
25d - olusturulan arrayin tum elemanlarini 5 ile carpin.
25e - olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [30]:
#25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu)
array25=np.arange(0,51,5)
array25

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
#25a - 20 den buyuk olan kac deger var.

array25[array25>20].size

6

In [32]:
#25b - 30’dan kucuk kac deger var
array25[array25<30].size


6

In [33]:
#25c - icerisinde 33 gecen kac deger var
array25[array25==33].size

0

In [34]:
#25d - olusturulan arrayin tum elemanlarini 5 ile carpin
array25*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250])

In [35]:
#25e - olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz
array25%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

26-) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; 
• orlamasini aliniz. 
• standart sapmasini aliniz. 
• varyansini aliniz. 
• median’ini aliniz. 
• en kucuk degeri bulunuz. 
• en buyuk degeri bulunuz. 

In [36]:
# 0 ile 1 arasinda 50 elamanli bir array olusturunuz
ar26 = np.linspace(0,1,50)
ar26

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [37]:
# • orlamasini aliniz.
print("Ortalamasi:",np.mean(ar26)) 
# • standart sapmasini aliniz. 
print("Standart Sapmasi:",np.std(ar26))
# • varyansini aliniz. 
print("Varyansi:",np.var(ar26))
# • median’ini aliniz. 
print("Median :",np.median(ar26))
# • en kucuk degeri bulunuz. 
print("Minimum :",np.min(ar26))
# • en buyuk degeri bulunuz. 
print("Maksimum :",np.max(ar26))



Ortalamasi: 0.5
Standart Sapmasi: 0.2945075446869757
Varyansi: 0.086734693877551
Median : 0.5
Minimum : 0.0
Maksimum : 1.0


** Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [ ]:
import time
import numpy as np

it_num=0
start=time.time()

while True:

    cont=True
    m1=np.random.rand(5,5)
    m2=np.random.rand(5,5)
    di_m=np.diag(m1-m2)
    it_num+=1

    for i in di_m:
        if i < -0.1 or i > 0.1:
            cont=False
            break

    if cont==True: 
        break

finish=time.time()

print("Total Time :",finish-start,"sec")
print("Total Iteration :",it_num)
print("Wanted Matrix :\n",m1-m2)